name: runbook
description: "An android app which contains useful utility tools."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.4
  file_picker: ^8.3.7
  archive: ^3.6.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
